### ISSUE TITLE
Some network requests have no status code

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/wpcom-proxy-request#24]
There are a few situations wherein a network request will not have a `statusCode` returned. 

One is described on #20, where failed network requests have no status code. See also #5, https://github.com/Automattic/wp-calypso/pull/15636#issuecomment-312860944, and #23. Please feel free to add more details for reproducing this issue if anyone has them.

Largely this has to do with the server-side part of the proxy. D6499 is an attempt to resolve that part of the issue.

**Comment by v18** [comment]
Steps to repro:

1. Run Calypso locally, go to `/me`
2. Select a new image to upload
3. Before clicking 'Change my photo', turn off the network in chrome dev tools
4. Click 'Change my photo'
5. See the success notice saying the new Gravatar was uploaded
6. See that the network request in fact failed, and no new Gravatar was uploaded to Gravatar.com

**Comment by sirbrillig** [comment]
Should be fixed by #29 and https://github.com/Automattic/wp-calypso/pull/16475
