### ISSUE TITLE
Properly handle connection errors

### ISSUE THREAD

**Issue by coreh** [Automattic/wpcom-proxy-request#5]
Make sure this fires the callback with an `err` argument if the internet is offline, or for some other reason it was not possible to send the proxy request.

**Comment by dmsnell** [comment]
@retrofox I'm noticing this too in automattic/wp-calypso#15636

although I keep getting lost trying to trace the execution through the message-passing I'm noticing that the failed network request is losing information when getting to its destination. it means that requests that return with `readyState = 0` and even `statusText = 'error'` are being returned as successful requests with `err = null, data = {}`.

obviously this is wrong and needs to be addressed. any help you can provide is greatly appreciated. if you can direct me to where I should be looking to find out where this information is getting dropped then I'm also happy to submit a PR with a possible solution.

thanks!
