### ISSUE TITLE
localstorage error

### ISSUE THREAD

**Issue by fredrocious** [Automattic/wpcom-proxy-request#7]
In Chrome, if you have Block 3rd party cookies and site data set, will now throw an error where previously with the same setting it would not.

![screenshot](https://cldup.com/H1S-yhih5G.png)

believe it was introduced here:

https://github.com/Automattic/wpcom-proxy-request/commit/bb1bfc53cef49c62a7e6fed90df0f7daa5f89fe2#diff-9ee7f4061d4c4cdec9f953d16e3c5b8eR505

cc: @rodrigoi

**Comment by rodrigoi** [comment]
This is a problem with the version of `debug` we are using. Looks like the problem was fixed on https://github.com/visionmedia/debug/commit/988592b640bf10faac2d8ebafa3135c0f3351123. @TooTallNate any chance of having a patched version of `debug` released? That should fix the problem.

**Comment by TooTallNate** [comment]
Ya sure thing. v2.1.2 published.
