### ISSUE TITLE
wpcom returns a malformed error object for empty responses

### ISSUE THREAD

**Issue by drewblaisdell** [Automattic/wpcom-proxy-request#9]
This resulted in a Calypso error downstream here: https://github.com/Automattic/calypso-pre-oss/issues/4052

When `wpcom-proxy-request` receives an empty response, it passes along a malformed error object (an array of single character strings spelling out 'error'):

![screen shot 2015-03-30 at 10 49 48 am](https://cloud.githubusercontent.com/assets/1130674/6900209/96ff8886-d6ca-11e4-8599-c50a5020f454.png)

It looks like this error comes from `onmessage`.

**Comment by gziolo** [comment]
I had similar issue with https://github.com/Automattic/calypso-pre-oss/pull/5109 when trying to get respobse using HEAD method:

```js
require( 'wpcom-proxy-request' )( {
	path: '/me',
	method: 'HEAD'
}, function() { } );
```

**Comment by gziolo** [comment]
Issue with HEAD method is now resolved with this change:
https://codereviewp2.wordpress.com/2015/04/09/allow-head-method-requests-for-wpcom-proxy-request/
This covers only cases when response was sent for HEAD method and GET method with 204 status.

**Comment by gziolo** [comment]
HEAD issue is nos resolved with recent pulic API chanfes.

**Comment by TooTallNate** [comment]
See https://codereviewp2.wordpress.com/2016/03/10/improved-http-level-errors-for-the-rest-proxy/ for fix.
